name: Build Binary
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y libssl-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build Binary
        run: pyinstaller --onefile password_generator.py
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: password-generator
          path: dist/password_generator
